In [5]:
import os
import pandas as pd
import env
import util

In [2]:
# Read csv file into pandas DataFrame.
file = "/Users/ultimate/codeup-data-science/pet_projects/2017-2018 FNDDS At A Glance - FNDDS Nutrient Values.xlsx"
df0 = pd.read_excel(file)
df0

,FNDDS Nutrient Values\n2017-2018 Food and Nutrient Database for Dietary Studies - At A Glance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68
0,Food code,Main food description,WWEIA Category number,WWEIA Category description,Energy (kcal),Protein (g),Carbohydrate (g),"Sugars, total\n(g)","Fiber, total dietary (g)",Total Fat (g),...,20:1\n(g),22:1\n(g),18:2\n(g),18:3\n(g),18:4\n(g),20:4\n(g),20:5 n-3\n(g),22:5 n-3\n(g),22:6 n-3\n(g),Water\n(g)
1,11000000,"Milk, human",9602,Human milk,70,1.03,6.89,6.89,0,4.38,...,0.04,0,0.374,0.052,0,0.026,0,0,0,87.5
2,11100000,"Milk, NFS",1004,"Milk, reduced fat",51,3.34,4.87,4.89,0,1.99,...,0.002,0,0.069,0.007,0,0.003,0,0.001,0,89.04
3,11111000,"Milk, whole",1002,"Milk, whole",60,3.28,4.67,4.81,0,3.2,...,0.004,0,0.115,0.012,0,0.004,0.001,0.002,0,88.1
4,11111100,"Milk, low sodium, whole",1002,"Milk, whole",61,3.1,4.46,4.46,0,3.46,...,0,0,0.078,0.05,0,0,0,0,0,88.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7079,99997802,Tomatoes as ingredient in omelet,9999,Not included in a food category,25,1.11,5.48,3.42,1.6,0.23,...,0,0,0.089,0.004,0,0,0,0,0,92.57
7080,99997804,Other vegetables as ingredient in omelet,9999,Not included in a food category,29,3.46,4.81,2.73,1.4,0.38,...,0,0,0.174,0.001,0,0,0,0,0,90.37
7081,99997810,Vegetables as ingredient in curry,9999,Not included in a food category,52,1.81,11.6,3.25,2.2,0.19,...,0,0,0.052,0.012,0,0,0,0,0,85.59
7082,99998130,Sauce as ingredient in hamburgers,9999,Not included in a food category,271,1.34,17.14,13.08,0.6,22.85,...,0.106,0.133,11.81,1.682,0,0.015,0,0,0.002,55.97
7083,99998210,Industrial oil as ingredient in food,9999,Not included in a food category,892,0,0,0,0,100,...,0.322,0.024,30.114,1.698,0,0,0,0,0,0

In [3]:
# Assign row as column headers
df0.columns = df0.iloc[0]

# Using DataFrame.rename()
df = df0.rename(columns=df0.iloc[1])

# Convert row to header and remove the row
df = df0.rename(columns=df0.iloc[0]).loc[1:]

# Using DataFrame.rename() to convert row to column header
df0.rename(columns=df0.iloc[1], inplace = True)

# Using DataFrame.values[]
header_row = df0.iloc[0]
df = pd.DataFrame(df0.values[1:], columns=header_row)

In [ ]:
df

,Food code,Main food description,WWEIA Category number,WWEIA Category description,Energy (kcal),Protein (g),Carbohydrate (g),"Sugars, total\n(g)","Fiber, total dietary (g)",Total Fat (g),...,20:1\n(g),22:1\n(g),18:2\n(g),18:3\n(g),18:4\n(g),20:4\n(g),20:5 n-3\n(g),22:5 n-3\n(g),22:6 n-3\n(g),Water\n(g)
0,11000000,"Milk, human",9602,Human milk,70,1.03,6.89,6.89,0,4.38,...,0.04,0,0.374,0.052,0,0.026,0,0,0,87.5
1,11100000,"Milk, NFS",1004,"Milk, reduced fat",51,3.34,4.87,4.89,0,1.99,...,0.002,0,0.069,0.007,0,0.003,0,0.001,0,89.04
2,11111000,"Milk, whole",1002,"Milk, whole",60,3.28,4.67,4.81,0,3.2,...,0.004,0,0.115,0.012,0,0.004,0.001,0.002,0,88.1
3,11111100,"Milk, low sodium, whole",1002,"Milk, whole",61,3.1,4.46,4.46,0,3.46,...,0,0,0.078,0.05,0,0,0,0,0,88.2
4,11111150,"Milk, calcium fortified, whole",1002,"Milk, whole",60,3.28,4.67,4.81,0,3.2,...,0.004,0,0.115,0.012,0,0.004,0.001,0.002,0,88.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7078,99997802,Tomatoes as ingredient in omelet,9999,Not included in a food category,25,1.11,5.48,3.42,1.6,0.23,...,0,0,0.089,0.004,0,0,0,0,0,92.57
7079,99997804,Other vegetables as ingredient in omelet,9999,Not included in a food category,29,3.46,4.81,2.73,1.4,0.38,...,0,0,0.174,0.001,0,0,0,0,0,90.37
7080,99997810,Vegetables as ingredient in curry,9999,Not included in a food category,52,1.81,11.6,3.25,2.2,0.19,...,0,0,0.052,0.012,0,0,0,0,0,85.59
7081,99998130,Sauce as ingredient in hamburgers,9999,Not included in a food category,271,1.34,17.14,13.08,0.6,22.85,...,0.106,0.133,11.81,1.682,0,0.015,0,0,0.002,55.97
7082,99998210,Industrial oil as ingredient in food,9999,Not included in a food category,892,0,0,0,0,100,...,0.322,0.024,30.114,1.698,0,0,0,0,0,0